import { Food } from "../shared/models/Food";


export const sample_foods: Food[] = [
    {
        id:'1',
        name: 'Pizza Pepperoni',
        cookTime: '10-20',
        price: 10,
        favorite: false,
        origins: ['italy'],
        stars: 4.5,
        imageUrl: 'assets/images/food-1.jpg',
        tags: ['FastFood', 'Pizza', 'Lunch'],
        description:'Very delicious',
      },
      {
        id:'2',
        name: 'Meatball',
        price: 20,
        cookTime: '20-30',
        favorite: true,
        origins: ['persia', 'middle east', 'china'],
        stars: 4.7,
        imageUrl: 'assets/images/food-2.jpg',
        tags: ['SlowFood', 'Lunch'],
        description:'Very delicious',
      },
      {
        id:'3',
        name: 'Hamburger',
        price: 5,
        cookTime: '10-15',
        favorite: false,
        origins: ['germany', 'us'],
        stars: 3.5,
        imageUrl: 'assets/images/food-3.jpg',
        tags: ['FastFood', 'Hamburger'],
        description:'Very delicious',
      },
      {
        id:'4',
        name: 'Fried Potatoes',
        price: 2,
        cookTime: '15-20',
        favorite: true,
        origins: ['belgium', 'france'],
        stars: 3.3,
        imageUrl: 'assets/images/food-4.jpg',
        tags: ['FastFood', 'Fry'],
        description:'Very delicious',
      },
      {
        id:'5',
        name: 'Chicken Soup',
        price: 11,
        cookTime: '40-50',
        favorite: false,
        origins: ['india', 'asia'],
        stars: 3.0,
        imageUrl: 'assets/images/food-5.jpg',
        tags: ['SlowFood', 'Soup'],
        description:'Very delicious',
      },
      {
        id:'6',
        name: 'Vegetables Pizza',
        price: 9,
        cookTime: '40-50',
        favorite: false,
        origins: ['italy'],
        stars: 4.0,
        imageUrl: 'assets/images/food-6.jpg',
        tags: ['FastFood', 'Pizza', 'Lunch'],
        description:'Very delicious',
      },

]